### ISSUE TITLE
Switching models without restarting the bot

### ISSUE THREAD

**Issue by jakobdylanc** [jakobdylanc/llmcord.py#54]
I'm thinking something like a settings menu that you can access by @'ing the bot with just a blank message. Then you're presented with a settings menu in the form of a special bot message, containing a bunch of checkboxes corresponding to the "characters" you've configured (aka models, each with a nickname and their own system prompt / parameters).

You can check as many boxes as you want to enable just 1 model or 5 models. If you enable 5 then you'll get 5 messages back each time you @ the bot; 1 from each model. This gives the added bonus of effortless multi-model prompting.

**Comment by tavdog** [comment]
I love this idea.

**Comment by jakobdylanc** [comment]
I await your PR (jk, unless)

**Comment by wastu01** [comment]
It would be better if we could type a prefix to reload the script, maybe by using cog mode.

**Comment by jakobdylanc** [comment]
Ideally the config.json should be something that you can set once and forget. I don't like the idea of having to constantly go back and forth between Discord and the config.json to reconfigure things. Sometimes it's unavoidable but I'd like to reduce it as much as possible.

Another option I'm considering is removing the `model` config option entirely. Instead, llmcord.py would automatically scan for all available models using the /v1/models/ endpoint of all your providers. And then something like a slash command to switch to any available model.

But...you'd also need a way to adjust the system prompt and API parameters, and save presets. Integrating all of this into Discord (as cleanly as possible) is tricky.

**Comment by jakobdylanc** [comment]
I just pushed an update that achieves this.

Now any changes you make to config.json are applied instantly, no restart required.

(Except the following settings which are only processed once at startup: "bot_token", "client_id", "status_message")

**Comment by wastu01** [comment]
Got it !
